# This is a basic workflow to help you get started with Actions

name: Update Today resources

# Controls when the action will run. 
on:
  # Triggers the workflow at the start of each month
  schedule:
    - cron: "5 4 1 * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-today:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Update today resource
        run: ./updateTodayResources.py

      # Create PR
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          token: ${{ secrets.GH_ACTION_ADMIN_TOKEN }}
          commit-message: Update today resources for the new month
          branch: update_today_resources
          delete-branch: true
          base: master
          title: Update today resources for new month
          body: ""
