name: Validate JSON

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: find . -name "resourceArraySchema.json"
      - name: Validate resource array JSON
        uses: Zingabopp/JsonValidate-Action@v1
        with:
          json-schema: ./schema/resourceArraySchema.json
          json-file: ./educate.json
    

