name: Validate JSON

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate resource array JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema/resourceArraySchema.json
          INPUT_JSONS: ./educate.json,./advocate.json,./act.json,./shop.json
          
      - name: Validate today resources JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema/todaySchema.json
          INPUT_JSONS: ./today.json
      
      - name: Validate state resources JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema/stateSchema.json
          INPUT_JSONS: ./states/alaska.json,./states/alabama.json,./states/arkansas.json,./states/arizona.json,./states/california.json,./states/colorado.json,./states/connecticut.json,./states/delaware.json,./states/florida.json,./states/georgia.json,./states/hawaii.json,./states/iowa.json,./states/idaho.json,./states/illinois.json,./states/indiana.json,./states/kansas.json,./states/kentucky.json,./states/louisiana.json,./states/massachusetts.json,./states/maryland.json,./states/maine.json,./states/michigan.json,./states/minnesota.json,./states/missouri.json,./states/mississippi.json,./states/montana.json,./states/north carolina.json,./states/north dakota.json,./states/nebraska.json,./states/new hampshire.json,./states/new jersey.json,./states/new mexico.json,./states/nevada.json,./states/new york.json,./states/ohio.json,./states/oklahoma.json,./states/oregon.json,./states/pennsylvania.json,./states/rhode island.json,./states/south carolina.json,./states/south dakota.json,./states/tennessee.json,./states/texas.json,./states/utah.json,./states/virginia.json,./states/vermont.json,./states/washington.json,./states/wisconsin.json,./states/west virginia.json,./states/wyoming.json
    

