name: Validate JSON

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate resource array JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema/resourceArraySchema.json
          INPUT_JSONS: ./educate.json,./advocate.json,./donate.json,./shop.json
      
      - name: Validate state JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema/stateSchema.json
          INPUT_JSONS: ./states/*.json
          
      - name: Validate today JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema/todaySchema.json
          INPUT_JSONS: ./today.json
    

